[package]
name = "mdq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
markdown = "1.0.0-alpha.16"
paste = "1.0"
regex = "1.10.4"
serde = "1"
serde_json = "1.0"

[dev-dependencies]
indoc = "2"
lazy_static = "1.4.0"
